#*******************************************************************************
# Copyright (c) 2017 AT&T Intellectual Property, [http://www.att.com]
#
# SPDX-License-Identifier:   MIT
#
#*******************************************************************************
server:
    port: 13020

management:
  port: 13021
  security:
    enabled: true

info:
  version: 1.0.0
  stage: dev

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  application:
    name: rcloud-rawgist-service
  cloud:
    config:
      enabled: false
      

security:
  user:
    name: admin
  basic:
    enabled: false

gists:
  root: /var/rcloud-rawgist-service/gists/