#*******************************************************************************
# Copyright (c) 2017 AT&T Intellectual Property, [http://www.att.com]
#
# SPDX-License-Identifier:   MIT
#
#*******************************************************************************

zuul:
  routes:
    default:
      path: /**
      url: ${github.api.url:https://api.github.com}
    gists:
     path: /**
     url: http://localhost:13020/
