#*******************************************************************************
# Copyright (c) 2017 AT&T Intellectual Property, [http://www.att.com]
#
# SPDX-License-Identifier:   MIT
#
#*******************************************************************************

################################################################################
# Application port. Change the value below to change the port this service
# is listening on.
################################################################################
#server:
#  port: 13020

################################################################################
# Management port. Change the value below to change the port the management
# services are listening on. This is protected by BASIC authentication details
# in the security section below.
################################################################################
#management:
#  port: 13021

################################################################################
# Security information settings administrative access to endpoints.
# Default user is 'admin' default password is generated on startup and printed
# out in the log file. To override these settings uncomment the lines below
# and specify your own password.
#
# The administrative endpoints are documented:
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
################################################################################
#security:
#  user:
#    name: admin
#    role: ADMIN
#    password: secret

################################################################################
# Gist Repository configuration:
# root:
#   Folder location for storing the gists. This needs to be writable by the 
#   rcloudgistservice user/group.
# lockTimeout:
#    Timeout to acquire read/write locks on a gist to prevent concurrent 
#    modification. This value is in seconds.
# keyservers:
#    The configuration block for the Session Key Servers. The immediate child
#    of this is the client_id name for the key server as is received in the
#    request from rcloud. A value of 'default' indicates that this is to 
#    be used if no matching client_id is specified for a key service 
#    configuration.
# keyservers.active:
#    Whether this configuration for the keyserver is active, default is true. 
# keyservers.host:
#    The host machine running the Session Key Server
# keyservers.port:
#    The port of the Session Key Server
# keyservers.url:
#    The URL template for the session key server.
# route.redirect:
#    A static route that when hit will return a redirect to the client
# route.redirect.from: 
#    The relative URL that this service uses to issue the redirect from.
# route.redirect.to:
#    The URL to redirect to
# route.redirect.copyparams:
#     Whether to copy the parameters from the request into the redirection URL.
#     defaults to 'true' if not specified
################################################################################
#gists:
#  root: /var/rcloud-gist-service/gists/
#  lockTimeout: 30
#  keyservers:
#    default:
#      host: 127.0.0.1
#      port: 4301
#      realm: rcloud
#      url: http://{host}:{port}/valid?token={token}&realm={realm}
#   route:
#    redirect:
#      from: '/login/*'
#      to: 'http://example.com'
#      copyparams: true



################################################################################
# Logging configuration:
#    config: The logback configuration file for logging.
#    file: The log file to write the log out to.
################################################################################
logging:
  config: logback.xml
  file: /var/log/${spring.application.name}/${spring.application.name}-file.log