server:
    port: 13010

management:
  port: 13011
  security:
    enabled: true

info:
  version: 1.0.0
  stage: dev

spring:
  application:
    name: rcloud-gist-service
  cloud:
    config:
      enabled: false

security:
  user:
    name: admin
  basic:
    enabled: false


zuul:
  routes:
    repos:
      path: /**
      url: ${github.api.url:https://api.github.com}
